### PR TITLE
Remove C code

### LINKED ISSUE #16: fatal flex scanner internal error--end of buffer missed
This error when I read .bib file. First I thought it happens because file is huge, with something like 5000 citations, so I exported only 4 citations from this set in bibtex format in a .bib format file. But even this 4 citations files does not work. I get the same error.

### LINKED ISSUE #42: Unable to recover after encountering two consecutive TOKEN_LBRACE "{"
As part of studying the parser more thoroughly for #40, I discovered what appears to be a critical bug. It occurs in both master and my WIP fixes for the rchk issues (which I have not yet added to the PR)

The bibtex entry that causes this:

```bibtex
encoding = "utf-8"

@String{{ BAZ = "Foo Bar Baz" }
```

And accessing it in R (I've stored the file in `inst/bib` locally):

```R
f <- file.path(system.file("bib", "parseError.bib", package = "bibtex"))
bib <- read.bib(f)
```

The second `{` correctly causes an error, but the grammar and/or error handling does not appear sufficient in order to recover correctly. Afterwards, I am unable to read any other `.bib` files - they fail and enter recovery as well.

In addition, a second call to `read.bib(f)` causes the R session to crash.

### PR DESCRIPTION
**Pull request by dieghernan**
Hi:

Following #46 and related to #45 , this PR removes the C code of the package, substituting it by pure R (base) code. I am aware this is a critical change to the package, so let me share some points of attention on this PR:

- Version bump to make clear that this is a dev version
- `trimws` has been updated to the latest version of the same function on R, see https://github.com/wch/r-source/blob/5ab79ec84040684c74dc9c901fde944fff6e8375/src/library/base/R/strwrap.R#L219-L229
- Some parameters have been deprecated:
   - `src` in `do_read_bib()` is not needed any more
   - `read.bib()`: `header` and `footer`. They were never actually used, see: https://github.com/ropensci/bibtex/blob/05a401cda1d4f1757a82979d181c4486a54755b1/R/bibtex.R#L162-L170
- A whole set of functions have been added to `utils.R`. This is actually the replacement of C in R code.
- An url on README has been updated following the `urlcheck`   package.
- There is a change on a snapshot. Actually now is correct, before was ommiting a part on the string:
```bibtex
@String{Rnews = "http://CRAN.R-project.org/doc/Rnews/" }
@String{Rnews2001-1 = rnews # "Rnews_2001-1.pdf"}
@String{Rnews2001-2 = rnews # "Rnews_2001-2.pdf"}
@String{Rnews2001-3 = rnews # "Rnews_2001-3.pdf"}

```
So `Rnews2001-3` should be parsed as  `rnews # "Rnews_2001-3.pdf` (http://CRAN.R-project.org/doc/Rnews/Rnews_2001-3.pdf)

- I run `revdepcheck::revdep_check()` succesfully. This is specially important for maintainers of the affected packages (@renozao, @sckott, @njahn82, @bwiernik, @mwmclean )

Comments welcome

This would also close #42 , fix #16

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -1,5 +1,5 @@
 Package: bibtex
-Version: 0.4.3
+Version: 0.4.3.9000
```
Comment (dieghernan) [inline DESCRIPTION:2]: Bump, this can be undone

File: R/bibtex.R [hunk 2]
```diff
@@ -1,6 +1,17 @@
 # backport of simplified trimws() (introduced in R-3.3.0)
-trimws <- function(x) {
-  sub("^[[:space:]]+", "", sub("[[:space:]]$", "", x))
+# See https://github.com/wch/r-source/blob/trunk/src/library/base/R/strwrap.R
+trimws <- function(x, which = c("both", "left", "right"),
```
Comment (dieghernan) [inline R/bibtex.R:3]: Updated version of the backport

File: R/bibtex.R [hunk 3]
```diff
@@ -196,10 +207,93 @@ findBibFile <- function(package) {
 #'
 #' @param file file name
 #' @param encoding encoding
-#' @param srcfile output of \code{\link{srcfile}}
+#' @param srcfile Deprecated
```
Comment (dieghernan) [inline R/bibtex.R:210]: Not needed nor used any more

File: R/bibtex.R [hunk 4]
```diff
@@ -215,10 +309,8 @@ do_read_bib <- function(file, encoding = "unknown", srcfile){
 #'         stats, stats4, tools and utils) are treated specially: this package
 #'         contains bibtex entries for these packages.
 #' @param encoding encoding
-#' @param header header of the citation list.
-#'        By default this is made from the \samp{Preamble} entries found in
-#'        the bib file.
-#' @param footer footer of the citation list
+#' @param header DEPRECATED.
+#' @param footer DEPRECATED
```
Comment (dieghernan) [inline R/bibtex.R:313]: Those were never used

File: R/bibtex.R [hunk 5]
```diff
@@ -257,17 +349,18 @@ read.bib <- function(file = findBibFile(package) ,
...
-                       error = function(e){
-                           if(!any(grepl("unprotect_ptr", e)))
-                              stop(geterrmessage(), call. = FALSE)
-                           else
-                              stop("Invalid bib file", call. = FALSE)
-                       }), warning = function(w){
-                             if( any( grepl( "syntax error, unexpected [$]end", w)))
-                               invokeRestart("muffleWarning")
-                           })
+    out <- tryCatch(do_read_bib(
```
Comment (dieghernan) [inline R/bibtex.R:352]: I needed to change this since C is not used any more. It gives the same messages, there is a test on that

File: README.md [hunk 6]
```diff
@@ -38,4 +38,4 @@ donate it to rOpenSci.
 - Get citation information for `bibtex` in R with `citation("bibtex")`
 - Please note that this package is released with a [Contributor Code of Conduct](https://ropensci.org/code-of-conduct/). By contributing to this project, you agree to abide by its terms.
 
-[![ropensci](http://ropensci.org/public_images/github_footer.png)](http://ropensci.org)
+[![ropensci](https://ropensci.org//public_images/github_footer.png)](https://ropensci.org/)
```
Comment (dieghernan) [inline README.md:41]: Just an update of the url, see `urlchecker::url_update()`

File: tests/testthat/_snaps/examples.md [hunk 7]
```diff
@@ -281,7 +281,7 @@
       pages = {20--23},
       month = {September},
       url = {http://CRAN.R-project.org/doc/Rnews/},
-      pdf = {rnewsRnews_2001-3.pdf},
+      pdf = {http://CRAN.R-project.org/doc/Rnews/Rnews_2001-3.pdf},
```
Comment (dieghernan) [inline tests/testthat/_snaps/examples.md:284]: This is now correct, before it just parsed the last part of the String, see https://ctan.javinator9889.com/biblio/bibtex/base/btxdoc.pdf:

File: tests/testthat/test-fatal-errors.R [hunk 8]
```diff
@@ -1,12 +1,10 @@
 test_that("Unbalanced braces", {
```
Comment (dieghernan) [inline tests/testthat/test-fatal-errors.R:1]: Now we can test fatal errors safely, R does not crash any more

**Comment by dieghernan** [comment]
I added some comments on the review tab to make easier to understand some things @coatless

File: R/bibtex.R (hunk 2 above)
Comment (coatless) [reply R/bibtex.R:3]: Should we consider a dependency on the [`{backports}`](https://github.com/r-lib/backports) package to automatically get up-to-speed? Though, as it stands now, we only have a dependency on one base package: `utils`. 

That said, we probably should bump the minimum version to at least R 3.6.* as we are not really testing if it works on R 3.0. Something to ponder for later on.

File: R/bibtex.R (hunk 3 above)
Comment (coatless) [reply R/bibtex.R:210]: We should probably also modify the function signature to use `''` and write a quick diagnostic message: 

```r
  if (!missing("srcfile"))
    message("`srcfile` argument is deprecated.")
```

File: R/bibtex.R [hunk 9]
```diff
@@ -196,10 +207,93 @@ findBibFile <- function(package) {
...
+    })
+
+    stringlines <- unlist(stringlines)
+
+    map_string_end <- tryCatch(parse_strings(map_string, stringlines),
+      warning = function(e) {
+        NULL
+      },
+      error = function(e) {
+        stop("Error when parsing strings of ",
```
Comment (coatless) [inline R/bibtex.R:270]: Is there a way we could indicate which line was problematic? Anything to make the error message more informative would be ideal here.

File: R/bibtex.R (hunk 4 above)
Comment (coatless) [reply R/bibtex.R:313]: See my previous note on deprecating arguments. 

If a previous argument was never used, perhaps we could also just exclude these arguments altogether in the next version?

File: R/utils.R [hunk 10]
```diff
@@ -0,0 +1,325 @@
+# Helper functions for do_read_bib()
+
+#' Parse (at)string keys
+#'
+#' Returns a table with all the string values and their value to be used on the
+#' `bib` file.
+#'
```
Comment (coatless) [inline R/utils.R:7]: Could we add an `@param` describing input? This is for long-term maintenance benefits as the function is internal.

File: R/utils.R [hunk 11]
```diff
@@ -0,0 +1,325 @@
...
+#' @noRd
+parse_strings <- function(map_string,
+                          stringlines) {
+
+  # This needs to be done in a loop, since strings can depend also
+  # on values of previous strings
+
+  parsed_string <- NULL
+
+  for (i in seq_len(length(stringlines))) {
```
Comment (coatless) [inline R/utils.R:17]: If `stringlines` is a vector, let's use `seq_along()` 

```suggestion
  for (i in seq_along(stringlines)) {
```

File: R/utils.R [hunk 12]
```diff
@@ -0,0 +1,325 @@
...
+    row <- map_string[i, ]
+    singleline <- stringlines[i]
+
+    map_braces <- check_balanced_braces(singleline, row$init)
+
+    # Extract string between first and last brace
+
+    f <- map_braces$pos[1]
```
Comment (coatless) [inline R/utils.R:25]: Could we improve the variable names? Maybe:

`f = first_bracket_position`
`l = last_bracket_position`.

File: R/utils.R [hunk 13]
```diff
@@ -0,0 +1,325 @@
...
+  treat_fields <- lapply(seq_len(length(fields)), function(x) {
+    string <- fields[x]
+    equalsign <- grep("=", strsplit(string, "")[[1]])
+    field_name <- trimws(substr(string, 1, equalsign - 1))
+    field_value <- trimws(substr(string, equalsign + 1, nchar(string)))
+
+    c(field_name, field_value)
+  })
+
+  field_names <- unlist(sapply(treat_fields, "[[", 1))
```
Comment (coatless) [inline R/utils.R:167]: Shouldn't `sapply()` return a vector by default? If not, let's use the `simplify = TRUE`.

File: R/utils.R [hunk 14]
```diff
@@ -0,0 +1,325 @@
...
+
+  entry_key <- gsub("@", "", unlist(strsplit(entry_key, "\\{")))
+  entry_name <- trimws(entry_key[1])
+  key_name <- trimws(entry_key[2])
+
+  # Now treat fields
+
+  fields <- formatted_bib[-1]
+
+  treat_fields <- lapply(seq_len(length(fields)), function(x) {
```
Comment (coatless) [inline R/utils.R:158]: Since we already switch `fields` over to a vector, let's take advantage of `seq_along()` again. 

```suggestion
  treat_fields <- lapply(seq_along(fields), function(x) {
```

File: README.md (hunk 6 above)
Comment (coatless) [reply README.md:41]: Thanks for running the `{urlchecker}`!

File: R/utils.R [hunk 15]
```diff
@@ -0,0 +1,325 @@
...
+    init <- rbind(init, row)
+  }
+
+  return(init)
+}
+
+#' Parse a single entry
+#'
+#' Returns an entry from a .bib file parsed into an R object
+#'
```
Comment (coatless) [inline R/utils.R:82]: Please add some documentation on parameters. (Even though it's an internal function.)

File: tests/testthat/_snaps/examples.md (hunk 7 above)
Comment (coatless) [reply tests/testthat/_snaps/examples.md:284]: Thanks for catching the update!

File: tests/testthat/test-fatal-errors.R (hunk 8 above)
Comment (coatless) [reply tests/testthat/test-fatal-errors.R:1]: Huzzah!

File: DESCRIPTION (hunk 1 above)
Comment (coatless) [reply DESCRIPTION:2]: Let's go 0.5.0 for the next CRAN release and, then, bump to 1.0.0.

File: revdep/README.md [hunk 16]
```diff
@@ -0,0 +1,28 @@
...
+# Dependencies
+
+|package  |old     |new        |<U+0394>  |
+|:--------|:-------|:----------|:--|
+|bibtex   |0.4.2.3 |0.4.3.9000 |*  |
+|glue     |1.6.0   |NA         |*  |
+|magrittr |2.0.1   |NA         |*  |
+|stringi  |1.7.6   |NA         |*  |
+|stringr  |1.4.0   |NA         |*  |
+
```
Comment (coatless) [inline revdep/README.md:26]: I'm not sure there are any dependencies w.r.t. `stringr` / `stringi` / `glue` / `magrittr`?

**Review by coatless — COMMENTED** [review]
Impressive work with the regular expressions! Reading through the regex, I'm not sure we'll unintentionally introduce another problem; but, the users will surely let us know. 

Outside of that, there are minor cleanups likely needed for long-term maintainability.

**Comment by dieghernan** [comment]
Thanks for this useful review. I would set this as a Draft until I tackle all your comments

File: DESCRIPTION (hunk 1 above)
Comment (dieghernan) [reply DESCRIPTION]: Done

File: R/bibtex.R (hunk 2 above)
Comment (dieghernan) [reply R/bibtex.R]: Good idea, I just added the `backports`, but agree on bumping the minimal R version as well

File: R/bibtex.R (hunk 3 above)
Comment (dieghernan) [reply R/bibtex.R:194]: Done! I also added a couple of tests on this

File: R/bibtex.R (hunk 4 above)
Comment (dieghernan) [reply R/bibtex.R:301]: Done. I would favor removing those on the next major version (1.0.0) just in case. For v0.5.0 I prefer to leave them, so we can get feedback

File: revdep/README.md (hunk 16 above)
Comment (dieghernan) [reply revdep/README.md:26]: This one is funny: On CRAN version, `bibtex` imports `stringr` (¿?), that imports `glue`, `magritt` and `stringr`, so I guess thats why they appear on the summary

https://cran.r-project.org/web/packages/bibtex/index.html
https://cran.r-project.org/web/packages/stringr/index.html

File: R/bibtex.R (hunk 9 above)
Comment (dieghernan) [reply R/bibtex.R:258]: I think we are already doing that, see this reprex. Do you wish to improve it in any way?

``` r
# Message on parsing entries
f <- file.path(system.file("bib", "badFormat.bib", package = "bibtex"))
bib <- read.bib(f)
#> ignoring entry 'brown:1963' (line 6) because :
#>  A bibentry of bibtype 'Book' has to specify the field: title
#> ignoring entry 'chambers+cleveland+kleiner+tukey:1983' (line 21) because :
#>  Invalid author/editor format.

# On unbalanced braces we throw an error indicating the problematic line
f2 <- system.file("bib", "unbalanced_braces.bib", package = "bibtex")
bib2 <- read.bib(f2)
#> Error: Unbalanced braces on entry (line 9). Invalid .bib file
#> Error: Invalid bib file
file <- f2
```

See https://github.com/ropensci/bibtex/blob/05a401cda1d4f1757a82979d181c4486a54755b1/inst/bib/badFormat.bib#L6-L10 and https://github.com/ropensci/bibtex/blob/05a401cda1d4f1757a82979d181c4486a54755b1/inst/bib/unbalanced_braces.bib#L9-L14

File: R/utils.R (hunk 10 above)
Comment (dieghernan) [reply R/utils.R:7]: I added documentation of params and also some examples on each internal function, hopefully that would help maintaining them

File: R/utils.R (hunk 15 above)
Comment (dieghernan) [reply R/utils.R:109]: Same, this is now documented and with examples

Comment (dieghernan) [reply R/utils.R:112]: And the examples are also part of the tests

File: R/utils.R (hunk 10 above)
Comment (dieghernan) [reply R/utils.R:7]: I added the examples also as tests on `test-utils.R`

File: R/utils.R (hunk 12 above)
Comment (dieghernan) [reply R/utils.R]: Done

File: R/utils.R (hunk 13 above)
Comment (dieghernan) [reply R/utils.R]: I went for `sapply`, i think is safer since the output is set on `FUN.VALUE`. This has been updated

**Comment by dieghernan** [comment]
Hi @coatless , just a quick reminder on this

**Comment by dieghernan** [comment]
Hi @maelle 

I re-runned checks, examples and snapshots after 8 months and I see no problems, so this is ready on my side. This PR would close #16 and close #42

**Comment by maelle** [comment]
Thanks @dieghernan!
@coatless would you be able to review this PR?

**Review by coatless — APPROVED** [review]

**Comment by coatless** [comment]
@dieghernan thanks for addressing the remaining issues. Sorry this sat for so long!
